<div class="main_slider">
    
    <!--<div class="page-title title-buttons">-->
        <h1><?php echo $this->__('YOUR SHOPPING CART ').date('d.m.Y',time());?></h1>
        <div class="spacer"> </div>
       <!-- <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>-->
    <!--</div>-->
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <div class="shopping_tbl_mian">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
             
                <table width="0" border="0" cellspacing="0" cellpadding="0">
                   
                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                     <tr>
                        <td class="name_tbl"><label><?php echo $this->__("name")?></label>&nbsp;</td>
                        <td class="art_tbl"><label><?php echo $this->__("ART.NR.")?></label>&nbsp;</td>
                        <td class="art_tbl"><label><?php echo $this->__("DIM.")?></label>&nbsp;</td>
                        <td class="art_tbl"><label><?php echo $this->__("SIZE")?></label>&nbsp;</td>
                        <td class="art_tbl"><label><?php echo $this->__("QTY")?></label>&nbsp;</td>
                        <td class="art_tbl"><label><?php echo $this->__("U.PRICE")?></label>&nbsp;</td>
                        <td class="saving_tbl"><label><?php echo $this->__("SAVING")?></label>&nbsp;</td>
                        <td class="total_tbl"><label><?php echo $this->__("TOTAL")?></label>&nbsp;</td>
                      </tr>
                     <div class="spacer"></div>
                     <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                     
                    <!--<tbody>
                    <?php //foreach($this->getItems() as $_item): ?>
                        <?php //echo $this->getItemHtml($_item) ?>
                    <?php //endforeach ?>
                    </tbody>-->
                </table>
                <div class="spacer"></div>
				<div class="total_div">
					<?php echo $this->getChildHtml('totals'); ?>
					<?php if(!$this->hasError()): ?>
					<ul class="checkout-types">
					<?php foreach ($this->getMethods('methods') as $method): ?>
						<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
						<li><?php echo $methodHtml; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
					</ul>
					<?php endif; ?>
				</div>
				<div class="spacer"></div>
				<div class="total_div">
					<!-- <?php echo $this->getChildHtml('coupon') ?> -->
					<div class="spacer"></div>
					<div class="tbl_button_main">
						<div class="tbl_buttn_01"><a href="#"> <?php echo $this->__('< CONTINUE SHOPPING') ?></a></div>
						<div class="tbl_buttn_01" id="margin_left_10">
							<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('UPDATE SHOPPING CART'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
						</div>	
						<!-- <div class="tbl_buttn_02">
							<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('PROCEED TO CHECKOUT'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
						</div> -->
						<div class="spacer"></div>
					</div>
					<div class="spacer"></div>
					 <div class="tbl_button_main">
						<div class="tbl_buttn_03"><a href="<?php echo $this->getBaseUrl(); ?>/wishlist/"> STORE SHOPPING LIST</a></div>
						<div class="spacer"></div>
					</div>
					<div class="spacer"></div>
				</div>
		<div class="spacer"> </div>
        </form>
		
    </div>
    <!--<div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
                <?php echo $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            </div>
        </div>
        <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>-->
</div>
<!--<tfoot>
                       <!-- <tr>
                            <td colspan="50" class="a-right">
                                <?php if($this->getContinueShoppingUrl()): ?>
                                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                <?php endif; ?>
                                <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                                <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                                -->
								<!--[if lt IE 8]>
                                <input type="hidden" id="update_cart_action_container" />
                                <script type="text/javascript">
                                //<![CDATA[
                                    Event.observe(window, 'load', function()
                                    {
                                        // Internet Explorer (lt 8) does not support value attribute in button elements
                                        $emptyCartButton = $('empty_cart_button');
                                        $cartActionContainer = $('update_cart_action_container');
                                        if ($emptyCartButton && $cartActionContainer) {
                                            Event.observe($emptyCartButton, 'click', function()
                                            {
                                                $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                $cartActionContainer.setValue('empty_cart');
                                            });
                                        }
    
                                    });
                                //]]>
                                </script>
                                <![endif]-->
                           <!-- </td>
                        </tr>
                    </tfoot>-->
					<script type="text/javascript">decorateTable('shopping-cart-table')</script>
					
					<div class="wrapper"><!--wrapper_start-->
    	
       
     
        
        <div class="spacer"></div>
		 <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<?php echo $this->getChildHtml('form_before') ?>
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
		<?php  //print_r($_post); ?>
		<?php  echo $this->getBlockHtml('formkey'); ?>
		
		<div class="main_div">
        	
              <div class="shopping_res_main">
			
					<?php	 
					     
						 $cartHelper = Mage::helper('checkout/cart');
						 $items2 = $cartHelper->getCart()->getItems();
						
						 $items = Mage::getSingleton('checkout/session')->getQuote();
						 $cartItems = $items->getAllVisibleItems();
						 $n = 1;
						 
						 foreach($cartItems as $item) {  
						  
						  $productId = $item->getProductId();
						  $product = Mage::getModel('catalog/product')->load($productId);
						  
				    ?>
					<?php 

					$attributeinfosize=$item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); 
					
					$optionattribut=$attributeinfosize['attributes_info'][0]['value'];
					$proitemid = $item->getId();
					?>
						   	<div class="product_cart_1">
                    	<div class="right_img_res"><img src="<?php echo $product->getImageUrl(); ?>" width="110" height="110" /></div>
                        <div class="product_left_text">
                            <label>PRODUCT NAME : <?php echo $item->getName();?></label>
                            <label>ART.NR.: <?php  echo $product->getArt_no();  ?></label>
                            <label>DIM.: <?php  echo $product->getDimensions();  ?></label>
                            <div class="spacer"></div>
                            <div class="size_div">
                            	<label>Size</label>
								
                           <input type="text" value="<?php  echo ($product->getAttributeText('size')!='')?$product->getAttributeText('size'):$optionattribut;?>" style="text-align: center;"/>
                            </div>
                            <div class="spacer"></div>
                        </div>
					
					<div class="product_right_text">
                        	<div class="close_icon">
							<a href="<?php echo $this->getBaseUrl().'/checkout/cart/delete/id/'.$item->getId().'/uenc/aHR0cDovLzE5Mi4xNjguMC4xNi9oYXNsYS9pbmRleC5waHAvY2hlY2tvdXQvY2FydC8,/'; ?>">
						
							<img src="<?php echo $this->getSkinUrl('/images/close_cross.jpg'); ?>" width="25" height="25" /></a>
							</div>
				
                            <div class="text_prudct_r_text">
                            	<label>QTY:</label>
                                <input type="text" name="cart[<?php echo $proitemid;?>][qty]" id ="proqty2<?php echo $n;?>"  value='<?php echo $item->getQty(); ?>' style="text-align: center;" onblur ="updatecart<?php echo $n;?>()"/>
                                <label>U. PRICE. <?php echo Mage::helper('core')->currency($item->getPrice()).',-'; ?></label>
                                <label>Saving</label>
                                <label>total : </label>
						<?php //echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode()) ; ?>
								
								<!--<input type="text"  value=""/>-->
								<div style="float: left;margin: 0px;margin-left: 10px;font-size: 10px;color: #4d4f54;width: 76px;height: 17px;text-align: center;margin-top: 5px;border: 1px solid #3b3d43;"><?php echo Mage::helper('core')->currency($item->getPrice()).',-'; ?></div>
                            	<div class="spacer"></div>
                            </div>
                        	<div class="spacer"></div>
                        </div>
                    </div>
					
					<script  type="text/javascript">
					function updatecart<?php echo $n;?>(){
					//alert(document.getElementById('proqty2<?php echo $n;?>').value);
					var finalqtyvalue = document.getElementById('proqty2<?php echo $n;?>').value;
					document.getElementById('proqty<?php echo $n;?>').value = finalqtyvalue;
					}
					</script>
					 
						 
				    <?php
					
					$n++;
						 }
						 
					?>
			
					
					
					
                 	<?php	 
					     
						 $items = Mage::getSingleton('checkout/session')->getQuote();
						 $cartItems = $items->getAllVisibleItems();
					     $n = 1;
						 foreach($cartItems as $item) {    
						  
						  $productId = $item->getProductId();
						  $product = Mage::getModel('catalog/product')->load($productId);
						  $proitemid = $item->getId();
				    ?>
					<?php 

					$attributeinfosize=$item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); 
					
					$optionattribut=$attributeinfosize['attributes_info'][0]['value'];

					?>
                    <div class="product_cart_320">
                    	<div class="right_img_res"><img src="<?php echo $product->getImageUrl(); ?>" width="110" height="110" /></div>
                        <div class="close_icon"><a href="<?php echo $this->getUrl('checkout/cart/delete', array('id' => $item->getProductId())); ?>"><img src="<?php echo $this->getSkinUrl('/images/close_cross.jpg'); ?>" width="25" height="25" /></a></div>
                        <div class="product_left_text">
                            <label>PRODUCT NAME  <?php echo $item->getName();?></label>
                            <label>ART.NR.: <?php  echo $product->getArt_no();  ?></label>
                            <label>DIM.: <?php  echo $product->getDimensions();  ?></label>
                            <div class="spacer"></div>
                            <div class="size_div">
                            	<label>Size</label>
                                <input type="text" value="<?php  echo ($product->getAttributeText('size')!='')?$product->getAttributeText('size'):$optionattribut;?>"  style="text-align: center;" readonly="readonly"/>
                            </div>
                            <div class="spacer"></div>
                             <div class="size_div">
                            	<label>QTY:</label>
                                <input type="text" name="cart[<?php echo $proitemid;?>][qty]" id ="proqty<?php echo $n;?>" value='<?php echo $item->getQty(); ?>'  style="text-align: center;" />
                            </div>
                            <label>U. PRICE. <?php echo Mage::helper('core')->currency($item->getPrice()).',-'; ?></label>
                            <div class="spacer"></div>
                           <div class="size_div">
                            	<label>Saving</label>
                                <input type="text" />
                            </div>
							
                            <label>total : <?php echo Mage::helper('core')->currency($item->getPrice()).',-'; ?></label>
                            <div class="spacer"></div>
                        </div>
                        <div class="spacer"> </div>
                    </div>
				
				    <?php	
					$n++;

					}   ?>
				
				<div class="total_div_res">
                       	<div class="total_right">
						<div class="sub_total">
						<?php echo $this->getChildHtml('totals'); ?>
						</div>
					   	
                        	<div class="spacer"></div>
                        </div>
                    	<div class="spacer"></div>
                    </div>
					
					<div class="spacer"></div>
					
					<div class="total_div_res">
                    <div class="discount_code">
                        <label>Discount code:</label>
                        <input type="text">
                    </div>
                    <div class="spacer"></div>
                    <div class="tbl_button_main" >
                        <div class="tbl_buttn_01"><a href="<?php echo $this->getBaseUrl(); ?>"> &lt; CONTINUE SHOPPING </a></div>
                       <!-- <div class="tbl_buttn_01" id="margin_left_10"><a href="#">UPDATE SHOPPING CART</a></div>-->
						<div class="tbl_buttn_01" id="margin_left_10">
							<button type="submit" name="update_cart_action" value="update_qty" title="UPDATE SHOPPING CART" class="button btn-update"><span><span>Update Shopping Cart</span></span></button>
						</div>
                       <div class="tbl_buttn_02"><a href="#" onclick="window.location='<?php echo $this->getBaseUrl(); ?>checkout/onepage/';"> PROCEED TO CHECKOUT</a></div>
                        <div class="spacer"></div>
                    </div>
                    <div class="spacer"></div>
                     <div class="tbl_button_main">
                        <div class="tbl_buttn_03"><a href="<?php echo $this->getBaseUrl(); ?>/wishlist/"> STORE SHOPPING LIST</a></div>
                        <div class="spacer"></div>
                    </div>
                    <div class="spacer"></div>
                </div>
				
                </div>
                <div class="spacer"></div>
			
        	<div class="spacer"></div>
        </div>
        </form>
        <div class="spacer"></div>
       
    	<div class="spacer"></div>
    </div><!--wrapper_end-->

