<?php
/**
 * BBS NetAxept, Norge
 *
 * LICENSE AND USAGE INFORMATION
 * It is NOT allowed to modify, copy or re-sell this file or any
 * part of it. Please contact us by email at post@trollweb.no or
 * visit us at www.trollweb.no/bbs if you have any questions about this.
 * Trollweb is not responsible for any problems caused by this file.
 *
 * Visit us at http://www.trollweb.no today!
 *
 * @category   Trollweb
 * @package    Trollweb_BBSNetAxept
 * @copyright  Copyright (c) 2009 Trollweb (http://www.trollweb.no)
 * @license    Single-site License
 *
 */

$logoUrl = $this->getLogo();
$_code=$this->getMethodCode();
$maskedPan = $this->getMaskedPan();
?>
<fieldset class="form-list">
    <?php if (!empty($logoUrl)): ?>
      <?php foreach ($logoUrl as $_url): ?>
      <img id="bbs_logo_<?php echo $_code; ?>" src="<?php echo $this->getSkinUrl($_url); ?>" />
      <?php endforeach; ?>
    <?php endif;?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <input type="hidden" name="payment[nets_mobile]" value="0" id="nets_mobile">
        <li>
            <?php echo $this->getRedirectText(); ?>
        </li>
    <?php if ($maskedPan): ?>
        <li class="easypayment">
          <div>Betal med lagret kort</div>
          <div><input name="payment[nets_easypayment_card]" type="checkbox" checked><span id="nets-pan"><?php echo $maskedPan ?></span></div>
        </li>
    <?php endif; ?>

    </ul>
</fieldset>

<script type="text/javascript">
 if (Modernizr.touch) {
    $('nets_mobile').value = 1
 }
</script>
