    <?php
		
		/***
		Add pagination in custome product listing
		company:tops tachnologies
		dev:nirav
		
		***/
		
		$actionName = $this->getAction()->getFullActionName();
		if ($actionName == 'catalog_category_view') // Category Page
		{
			$category = Mage::registry('current_category');
			$prodCol = $category->getProductCollection()->addAttributeToFilter('status', 1)->addAttributeToFilter('visibility', array('in' => array(Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG, Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH)));
			$tool = $this->getLayout()->createBlock('page/html_pager')->setLimit($this->getLayout()->createBlock('catalog/product_list_toolbar')->getLimit())->setCollection($prodCol); 
			$prolimit =  $this->getLayout()->createBlock('catalog/product_list_toolbar')->getLimit();
			$linkPrev = false;
			$linkNext = false;
			
			if ($tool->getCollection()->getSelectCountSql()) {
				if ($tool->getLastPageNum() > 1) {
					if (!$tool->isFirstPage()) {
						$linkPrev = true;
						if ($tool->getCurrentPage() == 2) {
							$url = explode('?', $tool->getPreviousPageUrl());
							$prevUrl = @$url[0];
						}
						else {
							$prevUrl = $tool->getPreviousPageUrl();
						}
					}
					if (!$tool->isLastPage()) {
						$linkNext = true;
						 $nextUrl = $tool->getNextPageUrl();
					}
				}
			}
			if ($linkPrev) echo '<link rel="prev" href="' . $prevUrl . '" />';
			if ($linkNext) echo '<link rel="next" href="' . $nextUrl . '" />';
		}
		   $nextUrl ;
		   if ($tool->isLastPage()) {
		
		    $islastpage = 1;
		   }
		   else
		   {
		     $islastpage = 0;
		   }
	?>
        
			
	<div class="pager">
		   
			<div class="pages">
			<!--<strong>Page:</strong>-->
			<ol> 
				<li>
					<a class="next i-next" href="<?php echo $nextUrl; ?>" title="Next" islast="<?php if($islastpage) { echo '1'; } else { echo '0'; } ?>" prolimit="<?php echo $prolimit; ?>" > </a>
				</li>
			</ol>
			</div>
	 
	</div>
	
	