<div class="main_slider" >
                <div class="banner">
                	<div class="cam_icon"><img src="http://hasla.indromen.com/media/wysiwyg/inspiration-banner-img_1.jpg" alt="" width="1000" height="390" /></div>
                </div>
                <div class="inspir_left_imgs">
                	<div class="inspire_thumb_main">
				
                        <div class="ins_prdct_01">
						<img src="http://hasla.indromen.com/media/wysiwyg/inspiration-img2_1.jpg" alt="">
                        	<div class="hover_div_name"><a href="#">PRODUCT NAME</a></div>
							
                        </div>
                        <div class="ins_prdct_02"><img src="http://hasla.indromen.com/media/wysiwyg/inspiration-img2_1.jpg" alt=""></div>
                        <div class="spacer"></div>
                    </div>
                    <div class="inspire_thumb_main">
                        <div class="ins_prdct_01"><img src="http://hasla.indromen.com/media/wysiwyg/inspiration-img2_1.jpg" alt=""></div>
                        <div class="ins_prdct_02"><img src="http://hasla.indromen.com/media/wysiwyg/inspiration-img2_1.jpg" alt=""></div>
                        <div class="spacer"></div>
                    </div>
                	<div class="spacer"></div>
                </div>
                <div class="inspir_right_imgs">
                	<div class="inpire_01"><img src="http://hasla.indromen.com/media/wysiwyg/inspiration-img1.jpg" alt=""></div>
                	<div class="spacer"></div>
                </div>
                <div class="spacer"></div>
                <div class="inspire_peragraph">
                	<label>TITLE HERE</label>
                    <p>
                    	voluptatem arum dit doloreration ent etus, nusdand anducia dolupie niatet aute pla sectum quia cum veliciis et am nis aut exere maio tende quam et etust inihictis excepro omnimus dem et eat esti dundae dolorrum hit fugitas ex et este por sin non pero beatibu struptusam, ut voluptibus rem que voluptatur rersper eruntis asimporior aut molupta.
                    </p>
                    <div class="spacer"></div>
                </div>
                <div class="spacer"></div>
            </div>