<?php if(count($this->getStores())>1): ?>
<div class="language-switcher" id="easyflags1">
    <?php 
	/*
	$i=0;
	foreach ($this->getStores() as $_lang): ?>
        <a href="<?php echo $_lang->getCurrentUrl() ?>"><?php if($this->htmlEscape($_lang->getName())=="Hasla Store") echo "English"; else echo "Norsk"; ?></a><?php if($i<1) { ?> | <?php }?>
    <?php 
			$i++;
	endforeach; 
	*/
	
	
	/*<a href="<?php echo $_lang->getCurrentUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/flags/' . $this->htmlEscape($_lang->getCode()) . '.gif') ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>" style="width: 22px;margin-top: 4px;"/></a> */
	?>
</div>
<?php endif; ?> 