<?php
$block_data = $this->getBlockData();
$blocks = $block_data['block'];
$banners = $block_data['banners'];
$click_url = $this->getUrl('bannerslider/index/click');
?>

<script src="<?php echo $this->getJsUrl('magestore/bannerslider/jquery.flexslider.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/bannerslider/flexslider.css') ?>" media="all" />
<script type="text/javascript">   
   // var j7 = jQuery.noConflict();
    jQuery(window).load(function() {
        jQuery('.flexslider-7-<?php echo $blocks['bannerslider_id'] ?>').flexslider({
            animation: "<?php echo $blocks['animationB'];?>",
            slideshowSpeed: <?php echo $blocks['slider_speed'];?>
            //minItems: 2,
            //maxItems: <?php echo $this->getMaxItem($blocks['max_item']); ?>            
        });
    });
</script>
	<?php if(count($banners) >1){ ?>
<div class="flexslider flexslider-7-<?php echo $blocks['bannerslider_id'] ?>">
    <ul class="slides" style="display: inline-block"> 
    <?php 
	echo '<pre/>';print_r(count($banners));
	echo count($banners);

	foreach ($banners as $banner): ?>
            <li>
                <a href="<?php echo $banner['click_url']?>" target="<?php echo $this->getTarget($banner['tartget'])?>" onclick="bannerClicks('<?php echo $banner['banner_id'] ?>','<?php echo $blocks['bannerslider_id'] ?>')" style="display:block"><img alt="<?php echo $banner['image_alt'];?>" src="<?php echo $this->getBannerImage($banner['image']); ?>"/></a>
            </li>
    <?php endforeach; 
	
	?>     
    <!-- items mirrored twice, total of 12 -->
    </ul>
</div>
<?php 
	
	}
	else
	{ 
	?> 
	<div class="flexslider">
    <ul class="slides" style="display: inline-block"> 
                <li style="display: list-item;">
                <a href="<?php echo $banners[0]['click_url']?>" target="<?php echo $this->getTarget($banners[0]['tartget'])?>" style="display:block"><img alt="<?php echo $banners[0]['image_alt'];?>" src="<?php echo $this->getBannerImage($banners[0]['image']); ?>"></a>
            </li>
            
    <!-- items mirrored twice, total of 12 -->
    </ul>
	</div> 
	<?php } ?>   
	
<script type="text/javascript">
        function bannerClicks(id_banner,id_slider){
		var click_url = '<?php echo $click_url;?>';
		banner_id = id_banner;
		new Ajax.Request(click_url,{
			method: 'post',
			parameters:{id_banner: banner_id, slider_id:id_slider},
			onFailure: '',
			onSuccess: ''
			
		});
		
	}
    </script>
