<div class="main_slider">
<h1>CONTACT HASLA</h1>
<div class="spacer"></div>
<div class="contact_hasla">
<h1><b>STORE IN OSLO</b></h1><br/><label><b>Hasla Markveien 54</b></label>
<label> 0554 Oslo<br /> T +47 92 27 87 77<br /> markveien@hasla.no </label>
<h1><b>STORE IN VALLE IN SETESDAL</b></h1>
<label> <b>Hasla Valle i Setesdal</b><br /> T +47 37 93 73 80<br /> post@hasla.no </label>
<h1><b>SUPPORT</b></h1>
<label> support@hasla.no </label>
<div class="spacer"></div>
</div>
<div class="spacer"></div>
</div>